### ISSUE TITLE
DB update stops after 1.2.1 update

### ISSUE THREAD

**Issue by clarkac1** [civicrm/org.civicrm.contactlayout#42]
After upgrading to 5.7 you are prompted to upgrade this extension to 1.2.1.  After this upgrade, a db update is required.  When run, it stops with "[Error: Upgrade org.civicrm.contactlayout to revision 1000] DB Error: no such field ".   See also [this ](https://civicrm.stackexchange.com/questions/27359/contact-layout-editor-db-update-crash-on-upgrade-to-1-2-1)
